# Generated by Django 3.2 on 2022-10-29 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('no', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pwd', models.IntegerField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
