# Generated by Django 3.2 on 2022-10-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('no', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pwd', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
