# Generated by Django 3.2 on 2022-10-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_product_shop_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
