# Generated by Django 3.2 on 2022-10-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pwd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_cart',
            name='pwd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop_cart',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
