# Generated by Django 3.2 on 2022-10-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='delivered',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='shop_cart',
            name='paid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
