# Generated by Django 3.2 on 2022-10-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_shop_cart_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop_cart',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
