# Generated by Django 3.2 on 2022-10-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20221029_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_cart',
            name='delivered',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shop_cart',
            name='paid',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
