# Generated by Django 3.2 on 2022-10-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_shop_cart_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_cart',
            name='a',
        ),
    ]
